# Generated by Django 4.1.4 on 2023-01-06 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100, null=True)),
                ('street_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(max_length=10, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(default='Poland', max_length=50)),
            ],
        ),
    ]
